---
name: "Build"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  build_image:
    name: Build guitarix container
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: |
          ./build.sh

